language: ruby
rvm:
- 2.6.2
notifications:
  slack:
    secure: iffJsOZYTrczBgj2YsWDnTz0MqpVRF2PhQH0POseTBWDF+33Sqot+193yFCkHD3nc0ldg87mNOW0V70JAj1mH0bFc3sheiOMz0JyKtCdfwaPCvnv2y+MvAHdeMPXjDS3XMNlB7g3MtaGfbddRxcNittPPVusWmuYre2Sfu1AYDU6KM3OEO7bBsonlpQETFkvHrU8Cc+ZgwJIAZMxOH+ubhtkyyPPVr4ThY7omfiJuzhRlJ06UXS/bbzXnlqCCPZ8md3YFnX4AnrNE5JZDEWF0kl+8ny7luI3tcxGqiitmND0QC3ZzohZGF7OWcw2MxA9/D+VjqtHmtg847d9xIdT9391J3ohyfcZ0s1GN6by+Vb4GwDuTWqwTdE5rdeLCz8j5G8+XDZccfnFRse5F6f7+2K9e0sKyrOChKwKHTCztACQl5i21k+6PECpfmxFLGEpjsiNpuXK3qmse0ntwvRMBtjCT+7ys9MihlDT6UoBm9+pTaSXtVgEPbgLmDzf2e3HUD5mJHhYW+Cs+q8NJelb+Y2e7R+ZnHqDL1wI+NkZKD/XP+xS6/9FZewsrzdY2flZHIvubKBmOHpvYe96iw3HYZU4x2QiijGW8IZIIoDsm0e3dfIkbA6sEzXVWNo1qQiHmw4hpiP+XwTTcZN87dyv53I9g0I+SLapQp4AVNrntmg=
